Squashed 'smartanthill/cc/embedded/' changes from 10e2c7b..c6f5b68
c6f5b68 Switch to the stable PlatformIO 2.2.0 release
64ed2e5 Implement hal_get_packet_bytes for wiring platform
158b50c hal_get_packet_bytes() and around
4bbe437 Listen for the all events from "wait_for" list
6cc284a Toward processing simple reply frames
b4a6891 Fix return type for getTime function in all platforms.
6196eaf Improve HAL for Wiring platform.
88393c0 Correct progmem handlers for msp430
6c7e30d Restore program for bodyparts
63ac2ae Fix fault issue with AVR
440e850 Remove program attribute for non AVR platform
453f6a9 fix of yet yet another warning
69bf6c7 addressing more warnings for wiring platform
8d7dbbc fixes in types
5998f17 addressing misc compiler warnings (client side)
60e4fb2 ordering project-level definitions
2c4a3c7 addressing warnings on client side (in progress)
af513ab addressing various compiler warnings (device side)
f288d30 fixes in 'void' platform hal_main and around
5d09069 disabling various test modes
55603ee bug fix in potential reading from progmem (saccp_protocol.c) and around
9b20641 toward proper implementation of ZEPTOVM_OP_SLEEP and minor fixes
312479a simple reply frame (with simpler processing) for Zepto VM level ONE
f8eff9c Add "voidavr" build environment
e622c95 Fix sa_main_init call
d99a242 Correct files with "hal_" relation
a2b98cc Replace hyphen with underscore in file names
cd68a1a adding "void" platform to platform selector
4c53d65 adding "void" platform (for testing purposes)
b01b2fe Simplifications and ordered-block assumption in zepto memory management
9f4777a Switch to PlatformIO develop (include/exclude feature)
507ec57 Rename win-lnx-common platform to desktop
c6d3e23 Merge Energia platform with Wiring
f99aa48 Rename Arduino platform to Wiring
8a5482d Fix broken build and implement Wiring HAL
ac09a30 Improve SADLP-Serial for Arduino
84fbed5 Preview of SADLP-Serial for Arduino
47a7561 toward zepto-vm (adding commands, etc; work in progress)
d9efd9e Fix functions renaming
f61fc70 function renaming
56c2e2d toward zepto-vm (adding commands)
6c91ca6 Implement auto-loading for plugins // Resolve #3
ef3536e Update build-cs
6261188 Update build-cs
335d793 separating device- and controller-side code
b96f9f9 Code for testing stack max size and minor fixes
9763e6a Move extra build options to SA_EMBEDDED_EXTRA_OPTIONS env variable
cab292d cleanup
8a928f5 Ignore stdint for Win platform
2d8df3d Fix standard integer types for WINLNXCOMMON.
bef0185 Refactor common defines between platforms
c05d414 Add bodypart_list to compile options
2814ef6 placing AES key to PROGMEM when available
82abf59 misc fixes
23cc44f Revert continue
91089ff adding respective changes to client side (comm stack)
e98ec79 Optimizing RAM usage
da6f5f4 Fix firmware building for MSP430
b6d1e3a Move different scripts to single Makefile
ed6c3b1 Initial version of astyle con
06d0eae AES S-box is now in PROGMEM (where applicable) // closing issue #8
146c79e restoring paths
d96790a Fixing bug in zepto-mem-mngmt.c; updating values of memory-related constants
358d96d Pass test just over uno (temporary solution for memory overflow)
e8d0b5d Fix undefined reference to 'clock_gettime'
75707cc Use eval instead bash -c
f29f705 Disable memory.h
42b4718 turning off obsolete counter system
1832985 Fix logical operation by bitwise
1d7318e Fix  'for' loop initial declaration
67a2f32 Revert internal loop to sa_main_loop()
943667b Emulator actual embodiment: big num arithmetic (incl. exponentiation); PROGMEM related issues
61a0197 Add sa-commlayer prototypes for MSP430
6f47119 Refactor sa-server; preparation for HAL commlayer
9691d4b Preparation for server refactoring
8910754 Implement base HAL for Energia platform // Resolve #7
15f47d7 Implement base HAL for Arduino platform // Resolve #4
a0e5871 Fix typo for file name
9d5e11d Add extern "C" linkage specification.
e7542d6 Rename hal-main.cpp to hal-main.c
6590d47 Add "ping" plugin
6d94e40 Minor changes for #ifdef and obsolete "default-test" name
fbc5679 Refactor "Smart Echo" plugin
d7c48cf Move "default plugin" to new plugins dir
02e8cac Remove -std=c99
9778429 Add init/loop frame for SA/HAL
96b70c8 Refactor build scripts for comm.stack and central unit
20cc350 Fix firmware building with @PlatformIO_Org
d04a3df Integrate with Travis CI
33270ab Refactoring with platform HALs
55e0066 Restruct project
e9cf979 switching to ZEPTO_DEBUG_PRINTF_XXX and ZEPTO_DEBUG_ASSERT
6b4beae Ignore PlatformIO temporary files
c84c535 Emulator actual embodiment: quick fix in calling eeprom-related routines
3e7ab3a Merge branch 'feature/emulator_actual_emb' into develop
6f33b3c Emulator actual embodiment: re-implementation of eeprom-related functionality; waiting; misc fixes
3915ea2 Emulator actual embodiment: adding sha-256
9153783 Emulator actual embodiment: update of hal-related code
6cae114 Emulator actual embodiment: SASP data persistent saving handling
359fcd4 Emulator actual embodiment: bodypart list related
8d85248 Preparation for SmartAnthill Embedded 2.0
b1aa784 Emulator actual embodiment: toward big num arithmetic (cleanup and further development pending)
df20193 Swap "saccp_protocol.c" from build commands
305ea55 Implement "clock_gettime" for Mac OS
5c98ff5 Add "exec" permission
0f7bf45 Emulator actual embodiment: moving SACCP out of central unit
0fb33f8 Emulator actual embodiment: build scripts
57e36b4 Emulator actual embodiment: cleanup
4fe7359 Emulator actual embodiment: commlayer based on zepto memory management; misc fixes
39d7104 Emulator actual embodiment: moving HAL-related functionality to emulator/hal; removing obsolete code; cleanup
1eb8baf Emulator actual embodiment: standardizing waiting in main loop of slave; removing obsolete code
51005f6 Emulator actual embodiment: addressing pre-C99 requirements
78a105f Emulator actual embodiment: further fixes for gcc
a0a95be Emulator actual embodiment: bug fixing
2a36243 Emulator actual embodiment: changes for *.cpp -> *.c (note: up to minor details it was a C-project yet from start)
772c9af Rename zepto-mem-mngmt.cpp to zepto-mem-mngmt.c
5ff7168 Rename yoctovm_protocol.cpp to yoctovm_protocol.c
295243a Rename test-generator.cpp to test-generator.c
3ecc5cd Rename saccp_protocol.cpp to saccp_protocol.c
c1d4bb6 Rename sagdp_protocol.cpp to sagdp_protocol.c
5a4fd19 Rename test-counters.cpp to test-counters.c
bcbaff9 Rename sasp_protocol.cpp to sasp_protocol.c
354886d Rename saoudp_protocol.cpp to saoudp_protocol.c
0f1c1c0 Rename sa_test_plugins.cpp to sa_test_plugins.c
d25a0db Rename sa_test_control_prog.cpp to sa_test_control_prog.c
8bdef35 Rename sa_server.cpp to sa_server.c
cbf590b Rename sa_client_comm_stack.cpp to sa_client_comm_stack.c
61e6b36 Rename sa_client_central_unit.cpp to sa_client_central_unit.c
0a55bf0 Rename sa_client.cpp to sa_client.c
fe0c878 Rename sa-unit-tests-aes-eax.cpp to sa-unit-tests-aes-eax.c
d92bd20 Rename sa-timer.cpp to sa-timer.c
9d53275 Rename sa-hal-time-provider.cpp to sa-hal-time-provider.c
75a2aeb Rename sa-eeprom.cpp to sa-eeprom.c
18c5d1b Rename sa-eax-128.cpp to sa-eax-128.c
c8a96bb Rename sa-commlayer.cpp to sa-commlayer.c
e6e7629 Rename sa-aes-128.cpp to sa-aes-128.c
cf19731 Emulator actual embodiment: cleanup mostly
60d46d7 Emulator actual embodiment: bug fixing
d9073ac Emulator actual embodiment: porting to gcc/linux (in progress); bug fixes
1c95c74 Emulator actual embodiment: misc fixes
76d233e Emulator actual embodiment: updates in timeout processing for SAGDP; misc fixes
af69ddd Emulator actual embodiment: cleanup and fixes
0f8cfc1 Emulator actual embodiment: client (master) side is now separated into two independent exe's (comm stack, and saccp and above) [further dev pending]
7e27ac9 Emulator actual embodiment: bug fixes in SACCP and testing plugin/control program
cec01c4 Emulator actual embodiment: SAGDP implementation further changes (master size) and cleanup
e0dfffd Emulator actual embodiment: SAGDP reimplementation (stack usage, data struct, etc)
d5718aa Emulator actual embodiment: starting SAoUDP protocol
495f63b Emulator actual embodiment: socket-based communication layer
eb5e201 Emulator actual embodiment: around explicit EXIT command
ec96991 Emulator actual embodiment: bug fixes in SACCP (now single correctly formed exec does go through)
b72886c Emulator actual embodiment: updating main loop with saccp; bug fixes
cd19b88 Emulator actual embodiment: toward SACCP for Master size
d85a6bd Emulator actual embodiment: SACCP protocol (device part so far)
d029213 Emulator actual embodiment: SASP code cleanup mostly
1b446ac Emulator actual embodiment: using type sa_uint48_t for SASP; some issues regarding endiannes
31075e6 Emulator actual embodiment: SASP code cleanup
0e7b5ff Emulator actual embodiment: SASP is now with EAX/AES
24fb591 Emulator actual embodiment: AES memory usage optimization
2b415ca Emulator actual embodiment: EAX unit tests and samples
bb4004c Emulator actual embodiment: EAX decryption and authentication
aba5fb5 Emulator actual embodiment: EAX is now good for arbitrary-size packets
c087170 Emulator actual embodiment: EAX (working on a single block so far)
8da6c60 Emulator actual embodiment: redesigned AES implementation
bf7d99c Emulator actual embodiment: adding implementation of AES-128 (interfaces are not final)
c81b19d Emulator actual embodiment: SAGDP process incoming packets in wait-local state; fixes for testing environment
23ff152 Emulator actual embodiment: enabling async packet receiving/packet processing on app level (testing environment)
426dd56 Emulator actual embodiment: all fields related to packet ID are now encoded uints (both in SASP and SAGDP packets)
37c4c6f Emulator actual embodiment: LSM is now a handle
419fa12 Emulator actual embodiment: fixes in test generation system; misc fixes
630880d Emulator actual embodiment: handle-based memory management (fixed handles so far)
fa5ebf0 Emulator actual embodiment: nonces as encoded uint's, misc fixes
c1492c2 Emulator actual embodiment: code cleanup
fc089d4 Emulator actual embodiment: memory handle-based mem management and parsing in protocol handlers and around
396bb7f Emulator actual embodiment: SASP handlers based on new memory management and parsing
4622159 emulator actual embodiment: memory management and parsing
1dc232d Merge branch 'feature/emulator_base' into develop
f2e4ced Emulator: now corresponds to SASP spec v.0.2.0 and SAGDP spec v.0.2.2
e7b55f9 Emulator base: further development of testing system (in particular, adding counters); bug fixing
77928b5 Emulator base: further dev of testing system; bug fixing
32c66d7 Merge branch 'develop' of https://github.com/smartanthill/smartanthill2_0-embedded into develop
ada6ba0 Simulator base: extended testing system, bug fixes, etc
3b9620f Update copyrights for source code and configuration files
d095148 Merge branch 'feature/emulator_base' of https://github.com/smartanthill/smartanthill2_0-embedded into develop
7c4d548 Simulator base: updating license section; revised types of fn parameters and vars; misc cleanup
da8da6b Emulator base: around nonce processing; further development of test system; bug fixes
9c2a6c9 Update to Twisted 15.0.0; Fix firmware uploading with PlatformIO 1.0 // Resolve #2
bbb3510 Emulator base: last packet can be re-sent while SAGDP is in idle state
b6f44a8 Simulator base: around requested-resend flag
3512da9 Simulator base: rebuilt test generation; fixed bug in SASP handler; getting packets async
66dfda0 Emulator base: working "old nonce" recovery
08a7798 Emulator base: main loop with working main scenario

git-subtree-dir: smartanthill/cc/embedded
git-subtree-split: c6f5b6835e2fc7081ae4c4e80e392c0be953bdf8